
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 16 15:27:08 CDT 2017
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FROM = 11;
  public static final int GEN = 14;
  public static final int INT = 15;
  public static final int SEMI = 2;
  public static final int SLASH = 5;
  public static final int MEDICAL = 17;
  public static final int SHOW = 7;
  public static final int MEETING = 20;
  public static final int AT = 10;
  public static final int WITH = 19;
  public static final int SPACE = 13;
  public static final int REMOVE = 6;
  public static final int CHANGE = 9;
  public static final int PERSONAL = 18;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int STR = 21;
  public static final int FREE = 4;
  public static final int SCHEDULE = 3;
  public static final int TO = 12;
  public static final int WORK = 16;
  public static final int DOUBLE = 8;
}

