
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 10 19:26:32 CDT 2017
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FROM = 10;
  public static final int GEN = 13;
  public static final int INT = 14;
  public static final int SEMI = 2;
  public static final int SLASH = 4;
  public static final int SHOW = 6;
  public static final int MEDICAL = 16;
  public static final int MEETING = 19;
  public static final int AT = 9;
  public static final int WITH = 18;
  public static final int SPACE = 12;
  public static final int REMOVE = 5;
  public static final int CHANGE = 8;
  public static final int PERSONAL = 17;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int STR = 20;
  public static final int SCHEDULE = 3;
  public static final int TO = 11;
  public static final int WORK = 15;
  public static final int DOUBLE = 7;
}

