
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 07 12:45:00 CDT 2017
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 15;
  public static final int SLASH = 3;
  public static final int TO = 10;
  public static final int PERSONAL = 12;
  public static final int REMOVE = 6;
  public static final int SEMI = 2;
  public static final int CHANGE = 7;
  public static final int EOF = 0;
  public static final int MEDICAL = 13;
  public static final int DOUBLE = 4;
  public static final int WORK = 11;
  public static final int error = 1;
  public static final int SPACE = 14;
  public static final int FROM = 9;
  public static final int AT = 8;
  public static final int SCHEDULE = 5;
}

