package agenda;
import java_cup.runtime.*;
import java.io.FileReader;

parser code{:
    public static void main(String args[])
    {
        try
        {
            SyntacticAnalyzer sa = new SyntacticAnalyzer(new LexicalAnalyzer(new FileReader(args[0])));
            Object result = sa.parse().value;
            System.out.println("Executed!");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
:}

terminal SEMI, SLASH, DOUBLE, SCHEDULE, REMOVE, CHANGE, AT, FROM, TO, WORK, PERSONAL, MEDICAL, SPACE;
terminal int INT;
non terminal Object create;


create ::= SCHEDULE WORK AT INT:month SLASH INT:day SLASH INT:year INT:hour DOUBLE INT:minutes 
{:
    System.out.format("\nWork date scheduled today at %d:%d on %d-%d-%d\n",hour,minutes,month,day,year);
:};